---
- name: install packages
  pkgng:
    name: "{{item}}"
    state: present
  with_items:
  - svnup
  - screen

- name: Setup data zpool
  zpool:
    name: "tank"
    devices: "ada0p4"
    raid_mode: "detect"

- name: Set data zpool options
  zfs:
    name: "tank"
    state: "present"
    atime: "off"
    checksum: fletcher4

- name: build ZFS file system
  zfs:
    name: "tank/FreeBSD"
    state: present
    mountpoint: /FreeBSD

- name: ensure src dir
  file:
    path: /FreeBSD/release10
    state: directory

- name: ensure src dir
  file:
    path: /FreeBSD/release10/src
    state: directory

- name: Configure svnup
  copy:
    src: svnup.conf
    dest: /usr/local/etc/svnup.conf

- name: ensure mount dir
  file:
    path: /media/cdrom
    state: directory

- name: mount installation files from mfsBSD image
  command: mount_cd9660 /dev/iso9660/MFSBSD /media/cdrom
  args:
    creates: /media/cdrom/mfsroot.gz

- name: Configure ploybsd build
  copy:
    src: binary.conf
    dest: /FreeBSD/ploybsd.conf
